In [64]:
# Dependencies
import numpy as np
import pandas as pd
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
from sqlalchemy import inspect

In [65]:
engine = create_engine("sqlite:///hawaii.sqlite")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [66]:
# Create our session (link) from Python to the DB
session = Session(engine)

## D1: Determine the Summary Statistics for June

In [67]:
#get columns for station table
inspector = inspect(engine)
for column in inspector.get_columns('station'):
    print(column['name'])

id
station
name
latitude
longitude
elevation

In [69]:
#get columns for measurement table
inspector = inspect(engine)
for column in inspector.get_columns('measurement'):
    print(column['name'])

id
station
date
prcp
tobs

In [62]:
#  Import the sqlalchemy extract function.
from sqlalchemy import extract

# Write a query that filters the Measurement table to retrieve the temperatures for the month of June. 

session.query(Measurement.tobs, Measurement.date).filter(func.extract('month', Measurement.date)== 6).all()

[(78.0, '2010-06-01'),
 (76.0, '2010-06-02'),
 (78.0, '2010-06-03'),
 (76.0, '2010-06-04'),
 (77.0, '2010-06-05'),
 (78.0, '2010-06-06'),
 (77.0, '2010-06-07'),
 (78.0, '2010-06-08'),
 (78.0, '2010-06-09'),
 (79.0, '2010-06-10'),
 (78.0, '2010-06-11'),
 (78.0, '2010-06-12'),
 (78.0, '2010-06-13'),
 (77.0, '2010-06-14'),
 (78.0, '2010-06-15'),
 (78.0, '2010-06-16'),
 (77.0, '2010-06-17'),
 (77.0, '2010-06-18'),
 (82.0, '2010-06-19'),
 (78.0, '2010-06-20'),
 (78.0, '2010-06-21'),
 (78.0, '2010-06-22'),
 (78.0, '2010-06-23'),
 (78.0, '2010-06-24'),
 (77.0, '2010-06-25'),
 (76.0, '2010-06-26'),
 (78.0, '2010-06-27'),
 (78.0, '2010-06-28'),
 (78.0, '2010-06-29'),
 (78.0, '2010-06-30'),
 (77.0, '2011-06-01'),
 (78.0, '2011-06-02'),
 (73.0, '2011-06-03'),
 (70.0, '2011-06-04'),
 (76.0, '2011-06-05'),
 (77.0, '2011-06-06'),
 (77.0, '2011-06-07'),
 (77.0, '2011-06-08'),
 (77.0, '2011-06-09'),
 (78.0, '2011-06-10'),
 (77.0, '2011-06-11'),
 (77.0, '2011-06-12'),
 (78.0, '2011-06-13'),
 (78.0, '2011-06-14'),
 (77.0, '2011-06-15'),
 (78.0, '2011-06-17'),
 (78.0, '2011-06-18'),
 (75.0, '2011-06-19'),
 (76.0, '2011-06-20'),
 (76.0, '2011-06-21'),
 (77.0, '2011-06-24'),
 (78.0, '2011-06-25'),
 (76.0, '2011-06-26'),
 (77.0, '2011-06-27'),
 (75.0, '2011-06-28'),
 (77.0, '2011-06-29'),
 (76.0, '2012-06-01'),
 (76.0, '2012-06-02'),
 (75.0, '2012-06-03'),
 (77.0, '2012-06-04'),
 (77.0, '2012-06-05'),
 (76.0, '2012-06-06'),
 (78.0, '2012-06-07'),
 (77.0, '2012-06-08'),
 (76.0, '2012-06-09'),
 (77.0, '2012-06-10'),
 (76.0, '2012-06-11'),
 (76.0, '2012-06-12'),
 (77.0, '2012-06-13'),
 (77.0, '2012-06-14'),
 (78.0, '2012-06-15'),
 (77.0, '2012-06-16'),
 (77.0, '2012-06-17'),
 (77.0, '2012-06-18'),
 (76.0, '2012-06-19'),
 (75.0, '2012-06-20'),
 (76.0, '2012-06-21'),
 (76.0, '2012-06-22'),
 (77.0, '2012-06-23'),
 (76.0, '2012-06-24'),
 (73.0, '2012-06-25'),
 (73.0, '2012-06-26'),
 (75.0, '2012-06-27'),
 (77.0, '2012-06-28'),
 (76.0, '2012-06-29'),
 (77.0, '2012-06-30'),
 (79.0, '2013-06-01'),
 (78.0, '2013-06-02'),
 (79.0, '2013-06-03'),
 (78.0, '2013-06-04'),
 (78.0, '2013-06-05'),
 (79.0, '2013-06-06'),
 (77.0, '2013-06-07'),
 (77.0, '2013-06-08'),
 (77.0, '2013-06-09'),
 (77.0, '2013-06-10'),
 (77.0, '2013-06-11'),
 (78.0, '2013-06-12'),
 (77.0, '2013-06-13'),
 (76.0, '2013-06-14'),
 (78.0, '2013-06-15'),
 (78.0, '2013-06-16'),
 (77.0, '2013-06-17'),
 (78.0, '2013-06-18'),
 (78.0, '2013-06-19'),
 (73.0, '2013-06-20'),
 (76.0, '2013-06-21'),
 (77.0, '2013-06-22'),
 (75.0, '2013-06-23'),
 (76.0, '2013-06-24'),
 (74.0, '2013-06-25'),
 (75.0, '2013-06-26'),
 (77.0, '2013-06-27'),
 (76.0, '2013-06-28'),
 (77.0, '2013-06-29'),
 (78.0, '2013-06-30'),
 (79.0, '2014-06-01'),
 (77.0, '2014-06-02'),
 (78.0, '2014-06-03'),
 (79.0, '2014-06-04'),
 (78.0, '2014-06-05'),
 (78.0, '2014-06-06'),
 (78.0, '2014-06-07'),
 (78.0, '2014-06-08'),
 (79.0, '2014-06-09'),
 (79.0, '2014-06-10'),
 (82.0, '2014-06-11'),
 (80.0, '2014-06-12'),
 (79.0, '2014-06-13'),
 (79.0, '2014-06-14'),
 (78.0, '2014-06-15'),
 (78.0, '2014-06-16'),
 (77.0, '2014-06-17'),
 (78.0, '2014-06-18'),
 (78.0, '2014-06-19'),
 (73.0, '2014-06-20'),
 (75.0, '2014-06-21'),
 (75.0, '2014-06-22'),
 (76.0, '2014-06-23'),
 (84.0, '2014-06-24'),
 (79.0, '2014-06-25'),
 (76.0, '2014-06-26'),
 (79.0, '2014-06-27'),
 (79.0, '2014-06-28'),
 (77.0, '2014-06-29'),
 (79.0, '2014-06-30'),
 (78.0, '2015-06-01'),
 (78.0, '2015-06-02'),
 (79.0, '2015-06-03'),
 (77.0, '2015-06-04'),
 (79.0, '2015-06-05'),
 (78.0, '2015-06-06'),
 (78.0, '2015-06-07'),
 (78.0, '2015-06-08'),
 (79.0, '2015-06-09'),
 (77.0, '2015-06-10'),
 (78.0, '2015-06-11'),
 (78.0, '2015-06-12'),
 (78.0, '2015-06-13'),
 (78.0, '2015-06-14'),
 (79.0, '2015-06-15'),
 (79.0, '2015-06-16'),
 (77.0, '2015-06-17'),
 (78.0, '2015-06-18'),
 (78.0, '2015-06-19'),
 (78.0, '2015-06-20'),
 (79.0, '2015-06-21'),
 (79.0, '2015-06-22'),
 (77.0, '2015-06-23'),
 (79.0, '2015-06-24'),
 (79.0, '2015-06-25'),
 (79.0, '2015-06-26'),
 (81.0, '2015-06-27'),
 (76.0, '2015-06-28'),
 (80.0, '2015-06-29'),
 (78.0, '2015-06-30'),
 (76.0, '2016-06-01'),
 (71.0, '2016-06-02'),
 (71.0, '2016-06-03'),
 (74.0, '2016-06-04'),
 (76.0, '2016-06-05'),
 (78.0, '2016-06-06'),
 (77.0, '2016-06-07'),
 (77.0, '2016-06-08'),
 (73.0, '2016-06-09'),
 (77.0, '2016-06-10'),
 (78.0, '2016-06-11'),
 (78.0, '2016-06-12'),
 (80.0, '2016-06-13'),
 (79.0, '2016-06-14'),
 (78.0, '2016-06-15'),
 (77.0, '2016-06-16'),
 (76.0, '2016-06-17'),
 (77.0, '2016-06-18'),
 (77.0, '2016-06-19'),
 (78.0, '2016-06-20'),
 (80.0, '2016-06-21'),
 (79.0, '2016-06-22'),
 (79.0, '2016-06-23'),
 (77.0, '2016-06-24'),
 (78.0, '2016-06-25'),
 (79.0, '2016-06-26'),
 (80.0, '2016-06-27'),
 (76.0, '2016-06-28'),
 (79.0, '2016-06-29'),
 (80.0, '2016-06-30'),
 (79.0, '2017-06-01'),
 (79.0, '2017-06-02'),
 (79.0, '2017-06-03'),
 (79.0, '2017-06-04'),
 (80.0, '2017-06-05'),
 (79.0, '2017-06-06'),
 (79.0, '2017-06-07'),
 (80.0, '2017-06-08'),
 (80.0, '2017-06-09'),
 (77.0, '2017-06-10'),
 (79.0, '2017-06-11'),
 (83.0, '2017-06-12'),
 (80.0, '2017-06-13'),
 (80.0, '2017-06-14'),
 (78.0, '2017-06-15'),
 (79.0, '2017-06-16'),
 (80.0, '2017-06-17'),
 (77.0, '2017-06-18'),
 (80.0, '2017-06-19'),
 (78.0, '2017-06-20'),
 (79.0, '2017-06-21'),
 (80.0, '2017-06-22'),
 (78.0, '2017-06-23'),
 (80.0, '2017-06-24'),
 (80.0, '2017-06-25'),
 (81.0, '2017-06-26'),
 (80.0, '2017-06-27'),
 (79.0, '2017-06-28'),
 (79.0, '2017-06-29'),
 (75.0, '2017-06-30'),
 (74.0, '2010-06-01'),
 (76.0, '2010-06-02'),
 (75.0, '2010-06-03'),
 (75.0, '2010-06-04'),
 (74.0, '2010-06-05'),
 (75.0, '2010-06-06'),
 (75.0, '2010-06-07'),
 (75.0, '2010-06-08'),
 (75.0, '2010-06-09'),
 (75.0, '2010-06-10'),
 (83.0, '2010-06-11'),
 (75.0, '2010-06-12'),
 (76.0, '2010-06-13'),
 (73.0, '2010-06-14'),
 (74.0, '2010-06-15'),
 (74.0, '2010-06-16'),
 (75.0, '2010-06-17'),
 (70.0, '2010-06-18'),
 (74.0, '2010-06-19'),
 (75.0, '2010-06-20'),
 (75.0, '2010-06-21'),
 (75.0, '2010-06-22'),
 (75.0, '2010-06-23'),
 (75.0, '2010-06-24'),
 (74.0, '2010-06-25'),
 (72.0, '2010-06-26'),
 (76.0, '2010-06-27'),
 (73.0, '2010-06-28'),
 (75.0, '2010-06-29'),
 (76.0, '2010-06-30'),
 (74.0, '2011-06-01'),
 (75.0, '2011-06-02'),
 (71.0, '2011-06-03'),
 (69.0, '2011-06-04'),
 (69.0, '2011-06-05'),
 (74.0, '2011-06-06'),
 (71.0, '2011-06-07'),
 (74.0, '2011-06-08'),
 (74.0, '2011-06-09'),
 (75.0, '2011-06-10'),
 (73.0, '2011-06-11'),
 (73.0, '2011-06-12'),
 (73.0, '2011-06-13'),
 (75.0, '2011-06-14'),
 (75.0, '2011-06-15'),
 (74.0, '2011-06-16'),
 (74.0, '2011-06-17'),
 (75.0, '2011-06-18'),
 (74.0, '2011-06-19'),
 (73.0, '2011-06-20'),
 (72.0, '2011-06-21'),
 (74.0, '2011-06-22'),
 (72.0, '2011-06-23'),
 (75.0, '2011-06-24'),
 (76.0, '2011-06-25'),
 (74.0, '2011-06-26'),
 (74.0, '2011-06-27'),
 (74.0, '2011-06-28'),
 (74.0, '2011-06-29'),
 (74.0, '2011-06-30'),
 (71.0, '2012-06-01'),
 (71.0, '2012-06-02'),
 (75.0, '2012-06-03'),
 (72.0, '2012-06-04'),
 (72.0, '2012-06-05'),
 (73.0, '2012-06-06'),
 (73.0, '2012-06-07'),
 (73.0, '2012-06-08'),
 (74.0, '2012-06-09'),
 (73.0, '2012-06-10'),
 (72.0, '2012-06-11'),
 (72.0, '2012-06-12'),
 (70.0, '2012-06-13'),
 (72.0, '2012-06-14'),
 (72.0, '2012-06-15'),
 (72.0, '2012-06-16'),
 (74.0, '2012-06-17'),
 (73.0, '2012-06-18'),
 (73.0, '2012-06-19'),
 (70.0, '2012-06-20'),
 (73.0, '2012-06-21'),
 (72.0, '2012-06-22'),
 (73.0, '2012-06-23'),
 (69.0, '2012-06-24'),
 (72.0, '2012-06-25'),
 (71.0, '2012-06-26'),
 (71.0, '2012-06-27'),
 (73.0, '2012-06-28'),
 (73.0, '2012-06-29'),
 (72.0, '2012-06-30'),
 (75.0, '2013-06-01'),
 (75.0, '2013-06-02'),
 (75.0, '2013-06-03'),
 (75.0, '2013-06-04'),
 (74.0, '2013-06-05'),
 (74.0, '2013-06-06'),
 (74.0, '2013-06-07'),
 (75.0, '2013-06-08'),
 (75.0, '2013-06-09'),
 (74.0, '2013-06-10'),
 (75.0, '2013-06-11'),
 (75.0, '2013-06-12'),
 (74.0, '2013-06-13'),
 (72.0, '2013-06-14'),
 (74.0, '2013-06-15'),
 (74.0, '2013-06-16'),
 (74.0, '2013-06-17'),
 (74.0, '2013-06-18'),
 (74.0, '2013-06-19'),
 (72.0, '2013-06-20'),
 (70.0, '2013-06-21'),
 (75.0, '2013-06-22'),
 (74.0, '2013-06-23'),
 (71.0, '2013-06-24'),
 (71.0, '2013-06-25'),
 (70.0, '2013-06-26'),
 (73.0, '2013-06-27'),
 (71.0, '2013-06-28'),
 (71.0, '2013-06-29'),
 (77.0, '2013-06-30'),
 (77.0, '2014-06-01'),
 (74.0, '2014-06-02'),
 (73.0, '2014-06-03'),
 (75.0, '2014-06-04'),
 (75.0, '2014-06-05'),
 (74.0, '2014-06-06'),
 (74.0, '2014-06-07'),
 (75.0, '2014-06-08'),
 (75.0, '2014-06-09'),
 (72.0, '2014-06-10'),
 (74.0, '2014-06-11'),
 (76.0, '2014-06-12'),
 (76.0, '2014-06-13'),
 (75.0, '2014-06-14'),
 (75.0, '2014-06-15'),
 (74.0, '2014-06-16'),
 (72.0, '2014-06-17'),
 (74.0, '2014-06-18'),
 (75.0, '2014-06-19'),
 (70.0, '2014-06-20'),
 (71.0, '2014-06-21'),
 (72.0, '2014-06-22'),
 (71.0, '2014-06-23'),
 (73.0, '2014-06-24'),
 (74.0, '2014-06-25'),
 (72.0, '2014-06-26'),
 (74.0, '2014-06-27'),
 (76.0, '2014-06-28'),
 (72.0, '2014-06-29'),
 (75.0, '2014-06-30'),
 (75.0, '2015-06-03'),
 (72.0, '2015-06-04'),
 (70.0, '2015-06-05'),
 (76.0, '2015-06-06'),
 (78.0, '2015-06-07'),
 (72.0, '2015-06-08'),
 (74.0, '2015-06-09'),
 (74.0, '2015-06-10'),
 (72.0, '2015-06-11'),
 (71.0, '2015-06-12'),
 (79.0, '2015-06-13'),
 (79.0, '2015-06-14'),
 (76.0, '2015-06-15'),
 (75.0, '2015-06-16'),
 (72.0, '2015-06-17'),
 (74.0, '2015-06-18'),
 (76.0, '2015-06-19'),
 (76.0, '2015-06-20'),
 (77.0, '2015-06-21'),
 (75.0, '2015-06-22'),
 (76.0, '2015-06-23'),
 (75.0, '2015-06-24'),
 (75.0, '2015-06-25'),
 (76.0, '2015-06-26'),
 (76.0, '2015-06-27'),
 (74.0, '2015-06-29'),
 (70.0, '2016-06-01'),
 (69.0, '2016-06-02'),
 (70.0, '2016-06-03'),
 (68.0, '2016-06-04'),
 (70.0, '2016-06-05'),
 (74.0, '2016-06-06'),
 (75.0, '2016-06-07'),
 (74.0, '2016-06-08'),
 (71.0, '2016-06-09'),
 (73.0, '2016-06-10'),
 (75.0, '2016-06-11'),
 (74.0, '2016-06-12'),
 (76.0, '2016-06-13'),
 (76.0, '2016-06-14'),
 (76.0, '2016-06-15'),
 (76.0, '2016-06-16'),
 (75.0, '2016-06-17'),
 (75.0, '2016-06-18'),
 (75.0, '2016-06-19'),
 (74.0, '2016-06-20'),
 (73.0, '2016-06-21'),
 (76.0, '2016-06-22'),
 (74.0, '2016-06-23'),
 (78.0, '2016-06-24'),
 (71.0, '2016-06-25'),
 (75.0, '2016-06-26'),
 (75.0, '2016-06-27'),
 (74.0, '2016-06-28'),
 (77.0, '2016-06-29'),
 (77.0, '2016-06-30'),
 (76.0, '2017-06-01'),
 (76.0, '2017-06-02'),
 (76.0, '2017-06-03'),
 (78.0, '2017-06-04'),
 (76.0, '2017-06-05'),
 (75.0, '2017-06-06'),
 (75.0, '2017-06-07'),
 (76.0, '2017-06-08'),
 (78.0, '2017-06-09'),
 (75.0, '2017-06-10'),
 (73.0, '2017-06-11'),
 (76.0, '2017-06-12'),
 (76.0, '2017-06-13'),
 (76.0, '2017-06-14'),
 (77.0, '2017-06-15'),
 (76.0, '2017-06-16'),
 (77.0, '2017-06-17'),
 (72.0, '2017-06-18'),
 (77.0, '2017-06-19'),
 (75.0, '2017-06-20'),
 (82.0, '2017-06-21'),
 (77.0, '2017-06-22'),
 (76.0, '2017-06-23'),
 (74.0, '2017-06-24'),
 (73.0, '2017-06-25'),
 (77.0, '2017-06-26'),
 (77.0, '2017-06-27'),
 (77.0, '2017-06-28'),
 (76.0, '2017-06-29'),
 (74.0, '2017-06-30'),
 (73.0, '2010-06-01'),
 (72.0, '2010-06-02'),
 (74.0, '2010-06-03'),
 (73.0, '2010-06-04'),
 (72.0, '2010-06-05'),
 (75.0, '2010-06-06'),
 (74.0, '2010-06-07'),
 (75.0, '2010-06-08'),
 (73.0, '2010-06-09'),
 (75.0, '2010-06-10'),
 (76.0, '2010-06-11'),
 (74.0, '2010-06-12'),
 (74.0, '2010-06-13'),
 (73.0, '2010-06-14'),
 (73.0, '2010-06-15'),
 (76.0, '2010-06-16'),
 (75.0, '2010-06-17'),
 (70.0, '2010-06-18'),
 (75.0, '2010-06-19'),
 (73.0, '2010-06-20'),
 (74.0, '2010-06-21'),
 (74.0, '2010-06-22'),
 (74.0, '2010-06-23'),
 (74.0, '2010-06-24'),
 (70.0, '2010-06-25'),
 (75.0, '2010-06-27'),
 (74.0, '2010-06-28'),
 (73.0, '2010-06-29'),
 (74.0, '2010-06-30'),
 (72.0, '2011-06-01'),
 (73.0, '2011-06-02'),
 (67.0, '2011-06-03'),
 (69.0, '2011-06-04'),
 (76.0, '2011-06-05'),
 (73.0, '2011-06-06'),
 (70.0, '2011-06-07'),
 (72.0, '2011-06-08'),
 (74.0, '2011-06-09'),
 (72.0, '2011-06-10'),
 (72.0, '2011-06-13'),
 (75.0, '2011-06-14'),
 (73.0, '2011-06-15'),
 (73.0, '2011-06-16'),
 (72.0, '2011-06-17'),
 (74.0, '2011-06-18'),
 (76.0, '2011-06-19'),
 (72.0, '2011-06-21'),
 (74.0, '2011-06-22'),
 (70.0, '2011-06-23'),
 (74.0, '2011-06-24'),
 (74.0, '2011-06-25'),
 (74.0, '2011-06-27'),
 (71.0, '2011-06-28'),
 (75.0, '2012-06-21'),
 (75.0, '2012-06-22'),
 (76.0, '2012-06-24'),
 (77.0, '2012-06-25'),
 (75.0, '2012-06-26'),
 (74.0, '2012-06-27'),
 (75.0, '2012-06-28'),
 (76.0, '2012-06-29'),
 (78.0, '2012-06-30'),
 (78.0, '2013-06-03'),
 (76.0, '2013-06-04'),
 (78.0, '2013-06-05'),
 (76.0, '2013-06-06'),
 (76.0, '2013-06-07'),
 (78.0, '2013-06-08'),
 (79.0, '2013-06-09'),
 (77.0, '2013-06-10'),
 (76.0, '2013-06-11'),
 (77.0, '2013-06-12'),
 (77.0, '2013-06-13'),
 (76.0, '2013-06-14'),
 (78.0, '2013-06-16'),
 (76.0, '2013-06-17'),
 (76.0, '2013-06-18'),
 (77.0, '2013-06-19'),
 (71.0, '2013-06-20'),
 (74.0, '2013-06-25'),
 (72.0, '2013-06-26'),
 (77.0, '2013-06-27'),
 (77.0, '2014-06-01'),
 (78.0, '2014-06-02'),
 (77.0, '2014-06-03'),
 (77.0, '2014-06-04'),
 (76.0, '2014-06-05'),
 (75.0, '2014-06-06'),
 (79.0, '2014-06-07'),
 (75.0, '2014-06-09'),
 (73.0, '2014-06-10'),
 (76.0, '2014-06-11'),
 (78.0, '2014-06-12'),
 (77.0, '2014-06-13'),
 (78.0, '2014-06-14'),
 (76.0, '2014-06-16'),
 (75.0, '2014-06-17'),
 (76.0, '2014-06-18'),
 (77.0, '2014-06-19'),
 (74.0, '2014-06-20'),
 (78.0, '2014-06-21'),
 (77.0, '2014-06-23'),
 (77.0, '2014-06-24'),
 (74.0, '2014-06-25'),
 (74.0, '2014-06-26'),
 (78.0, '2014-06-27'),
 (79.0, '2014-06-29'),
 (79.0, '2014-06-30'),
 (78.0, '2015-06-01'),
 (75.0, '2015-06-03'),
 (76.0, '2015-06-04'),
 (78.0, '2015-06-05'),
 (78.0, '2015-06-06'),
 (74.0, '2015-06-08'),
 (78.0, '2015-06-09'),
 (77.0, '2015-06-10'),
 (76.0, '2015-06-11'),
 (78.0, '2015-06-12'),
 (78.0, '2015-06-14'),
 (78.0, '2015-06-15'),
 (78.0, '2015-06-16'),
 (74.0, '2015-06-17'),
 (79.0, '2015-06-18'),
 (77.0, '2015-06-19'),
 (73.0, '2015-06-20'),
 (79.0, '2015-06-21'),
 (79.0, '2015-06-22'),
 (78.0, '2015-06-23'),
 (77.0, '2015-06-24'),
 (78.0, '2015-06-25'),
 (78.0, '2015-06-26'),
 (80.0, '2015-06-27'),
 (80.0, '2015-06-28'),
 (79.0, '2015-06-29'),
 (74.0, '2015-06-30'),
 (71.0, '2016-06-01'),
 (74.0, '2016-06-02'),
 (75.0, '2016-06-03'),
 (75.0, '2016-06-07'),
 (74.0, '2016-06-08'),
 (76.0, '2016-06-09'),
 (75.0, '2016-06-10'),
 (77.0, '2016-06-11'),
 (77.0, '2016-06-12'),
 (79.0, '2016-06-13'),
 (79.0, '2016-06-14'),
 (78.0, '2016-06-15'),
 (79.0, '2016-06-16'),
 (73.0, '2016-06-17'),
 (78.0, '2016-06-18'),
 (79.0, '2016-06-19'),
 (80.0, '2016-06-20'),
 (76.0, '2016-06-21'),
 (79.0, '2016-06-22'),
 (79.0, '2016-06-23'),
 (77.0, '2016-06-24'),
 (80.0, '2016-06-25'),
 (79.0, '2016-06-26'),
 (78.0, '2016-06-27'),
 (78.0, '2016-06-28'),
 (79.0, '2016-06-29'),
 (78.0, '2016-06-30'),
 (81.0, '2017-06-01'),
 (78.0, '2017-06-02'),
 (80.0, '2017-06-03'),
 (79.0, '2017-06-04'),
 (81.0, '2017-06-05'),
 (80.0, '2017-06-06'),
 (81.0, '2017-06-07'),
 (79.0, '2017-06-08'),
 (81.0, '2017-06-09'),
 (78.0, '2017-06-10'),
 (79.0, '2017-06-11'),
 (79.0, '2017-06-12'),
 (75.0, '2017-06-13'),
 (79.0, '2017-06-14'),
 (78.0, '2017-06-15'),
 (80.0, '2017-06-16'),
 (78.0, '2017-06-17'),
 (77.0, '2017-06-18'),
 (78.0, '2017-06-19'),
 (79.0, '2017-06-20'),
 (76.0, '2017-06-23'),
 (80.0, '2017-06-26'),
 (76.0, '2017-06-29'),
 (81.0, '2017-06-30'),
 (77.0, '2010-06-01'),
 (76.0, '2010-06-02'),
 (77.0, '2010-06-03'),
 (75.0, '2010-06-04'),
 (76.0, '2010-06-07'),
 (79.0, '2010-06-08'),
 (79.0, '2010-06-09'),
 (77.0, '2010-06-10'),
 (76.0, '2010-06-15'),
 (77.0, '2010-06-16'),
 (76.0, '2010-06-17'),
 (73.0, '2010-06-18'),
 (76.0, '2010-06-21'),
 (77.0, '2010-06-22'),
 (77.0, '2010-06-23'),
 (78.0, '2010-06-24'),
 (77.0, '2010-06-25'),
 (76.0, '2010-06-28'),
 (78.0, '2010-06-29'),
 (78.0, '2010-06-30'),
 (75.0, '2011-06-01'),
 (77.0, '2011-06-02'),
 (65.0, '2011-06-03'),
 (76.0, '2011-06-06'),
 (74.0, '2011-06-07'),
 (76.0, '2011-06-08'),
 (76.0, '2011-06-09'),
 (77.0, '2011-06-13'),
 (77.0, '2011-06-14'),
 (76.0, '2011-06-15'),
 (77.0, '2011-06-16'),
 (76.0, '2011-06-17'),
 (77.0, '2011-06-20'),
 (74.0, '2011-06-21'),
 (76.0, '2011-06-22'),
 (73.0, '2011-06-23'),
 (75.0, '2011-06-24'),
 (76.0, '2011-06-27'),
 (75.0, '2011-06-28'),
 (76.0, '2011-06-29'),
 (75.0, '2011-06-30'),
 (74.0, '2012-06-01'),
 (74.0, '2012-06-04'),
 (74.0, '2012-06-05'),
 (74.0, '2012-06-06'),
 (76.0, '2012-06-07'),
 (76.0, '2012-06-08'),
 (77.0, '2012-06-12'),
 (77.0, '2012-06-13'),
 (78.0, '2012-06-14'),
 (73.0, '2012-06-15'),
 (75.0, '2012-06-18'),
 (72.0, '2012-06-19'),
 (76.0, '2012-06-20'),
 (76.0, '2012-06-21'),
 (73.0, '2012-06-22'),
 (74.0, '2012-06-25'),
 (72.0, '2012-06-26'),
 (76.0, '2012-06-27'),
 (76.0, '2012-06-28'),
 (76.0, '2012-06-29'),
 (78.0, '2013-06-03'),
 (78.0, '2013-06-04'),
 (78.0, '2013-06-05'),
 (78.0, '2013-06-06'),
 (75.0, '2013-06-07'),
 (77.0, '2013-06-10'),
 (73.0, '2013-06-12'),
 (78.0, '2013-06-13'),
 (75.0, '2013-06-14'),
 (73.0, '2013-06-17'),
 (77.0, '2013-06-18'),
 (80.0, '2013-06-19'),
 (70.0, '2013-06-20'),
 (78.0, '2013-06-21'),
 (72.0, '2013-06-25'),
 (78.0, '2013-06-26'),
 (72.0, '2013-06-27'),
 (78.0, '2013-06-28'),
 (77.0, '2014-06-02'),
 (79.0, '2014-06-03'),
 (77.0, '2014-06-04'),
 (78.0, '2014-06-05'),
 (74.0, '2014-06-06'),
 (79.0, '2014-06-09'),
 (79.0, '2014-06-10'),
 (79.0, '2014-06-12'),
 (79.0, '2014-06-13'),
 (77.0, '2014-06-16'),
 (79.0, '2014-06-17'),
 (78.0, '2014-06-18'),
 (80.0, '2014-06-19'),
 (81.0, '2014-06-20'),
 (81.0, '2014-06-27'),
 (78.0, '2015-06-10'),
 (77.0, '2015-06-12'),
 (78.0, '2015-06-15'),
 (79.0, '2015-06-16'),
 (77.0, '2015-06-17'),
 (79.0, '2015-06-18'),
 (80.0, '2015-06-19'),
 (79.0, '2015-06-22'),
 (78.0, '2015-06-23'),
 (79.0, '2015-06-24'),
 (79.0, '2015-06-25'),
 (79.0, '2015-06-29'),
 (81.0, '2015-06-30'),
 (64.0, '2016-06-01'),
 (65.0, '2016-06-02'),
 (75.0, '2016-06-03'),
 (76.0, '2016-06-06'),
 (78.0, '2016-06-07'),
 (77.0, '2016-06-08'),
 (75.0, '2016-06-09'),
 (78.0, '2016-06-13'),
 (81.0, '2016-06-14'),
 (78.0, '2016-06-15'),
 (76.0, '2016-06-16'),
 (73.0, '2016-06-17'),
 (74.0, '2016-06-20'),
 (76.0, '2016-06-21'),
 (78.0, '2016-06-22'),
 (79.0, '2016-06-23'),
 (78.0, '2016-06-24'),
 (72.0, '2016-06-27'),
 (78.0, '2016-06-28'),
 (80.0, '2016-06-29'),
 (81.0, '2016-06-30'),
 (79.0, '2017-06-02'),
 (78.0, '2017-06-05'),
 (80.0, '2017-06-06'),
 (80.0, '2017-06-07'),
 (78.0, '2017-06-08'),
 (80.0, '2017-06-09'),
 (81.0, '2017-06-13'),
 (78.0, '2017-06-14'),
 (77.0, '2017-06-15'),
 (78.0, '2017-06-16'),
 (78.0, '2017-06-19'),
 (77.0, '2017-06-20'),
 (76.0, '2017-06-21'),
 (81.0, '2017-06-22'),
 (76.0, '2017-06-23'),
 (82.0, '2017-06-26'),
 (80.0, '2017-06-27'),
 (80.0, '2017-06-28'),
 (79.0, '2017-06-29'),
 (74.0, '2017-06-30'),
 (69.0, '2010-06-01'),
 (70.0, '2010-06-02'),
 (67.0, '2010-06-03'),
 (70.0, '2010-06-04'),
 (73.0, '2010-06-05'),
 (73.0, '2010-06-06'),
 (72.0, '2010-06-09'),
 (72.0, '2010-06-10'),
 (77.0, '2010-06-11'),
 (70.0, '2010-06-12'),
 (78.0, '2010-06-13'),
 (73.0, '2010-06-15'),
 (75.0, '2010-06-17'),
 (70.0, '2010-06-18'),
 (74.0, '2010-06-19'),
 (77.0, '2010-06-20'),
 (69.0, '2010-06-22'),
 (73.0, '2010-06-23'),
 (73.0, '2010-06-24'),
 (74.0, '2010-06-25'),
 (73.0, '2010-06-28'),
 (72.0, '2010-06-29'),
 (75.0, '2010-06-30'),
 (73.0, '2011-06-08'),
 (76.0, '2011-06-09'),
 (74.0, '2011-06-12'),
 (76.0, '2011-06-13'),
 (73.0, '2011-06-14'),
 (76.0, '2011-06-15'),
 (76.0, '2011-06-16'),
 (78.0, '2011-06-20'),
 (75.0, '2011-06-21'),
 (77.0, '2011-06-22'),
 (75.0, '2012-06-01'),
 (73.0, '2012-06-14'),
 (76.0, '2012-06-21'),
 (71.0, '2012-06-26'),
 (71.0, '2012-06-29'),
 (76.0, '2010-06-01'),
 (76.0, '2010-06-02'),
 (76.0, '2010-06-03'),
 (73.0, '2010-06-04'),
 (78.0, '2010-06-05'),
 (77.0, '2010-06-06'),
 (77.0, '2010-06-07'),
 (77.0, '2010-06-08'),
 (78.0, '2010-06-09'),
 (78.0, '2010-06-10'),
 (76.0, '2010-06-11'),
 (76.0, '2010-06-12'),
 (79.0, '2010-06-13'),
 (74.0, '2010-06-14'),
 (75.0, '2010-06-15'),
 (76.0, '2010-06-16'),
 (75.0, '2010-06-17'),
 (73.0, '2010-06-18'),
 (76.0, '2010-06-19'),
 (78.0, '2010-06-20'),
 (76.0, '2010-06-21'),
 (79.0, '2010-06-22'),
 (77.0, '2010-06-23'),
 (76.0, '2010-06-24'),
 (74.0, '2010-06-25'),

In [46]:
#  Convert the June temperatures to a list.
june_temps = []
june_temps = session.query(Measurement.tobs).filter(func.extract('month', Measurement.date)== 6).all()

True

In [52]:
# Create a DataFrame from the list of temperatures for the month of June. 
june_temps_df = pd.DataFrame(june_temps, columns = ['June Temps'])
june_temps_df

      June Temps
0           78.0
1           76.0
2           78.0
3           76.0
4           77.0
...          ...
1695        79.0
1696        74.0
1697        74.0
1698        76.0
1699        75.0

[1700 rows x 1 columns]

In [53]:
# Calculate and print out the summary statistics for the June temperature DataFrame.
june_temps_df.describe()

        June Temps
count  1700.000000
mean     74.944118
std       3.257417
min      64.000000
25%      73.000000
50%      75.000000
75%      77.000000
max      85.000000

## D2: Determine the Summary Statistics for December

In [57]:
# Write a query that filters the Measurement table to retrieve the temperatures for the month of December.
session.query(Measurement.tobs).filter(func.extract('month', Measurement.date)== 12).all()

[(76.0,),
 (74.0,),
 (74.0,),
 (64.0,),
 (64.0,),
 (67.0,),
 (77.0,),
 (66.0,),
 (69.0,),
 (68.0,),
 (68.0,),
 (71.0,),
 (74.0,),
 (67.0,),
 (66.0,),
 (69.0,),
 (71.0,),
 (70.0,),
 (70.0,),
 (74.0,),
 (74.0,),
 (71.0,),
 (75.0,),
 (75.0,),
 (72.0,),
 (69.0,),
 (68.0,),
 (73.0,),
 (74.0,),
 (73.0,),
 (73.0,),
 (73.0,),
 (73.0,),
 (71.0,),
 (73.0,),
 (73.0,),
 (77.0,),
 (72.0,),
 (71.0,),
 (73.0,),
 (70.0,),
 (73.0,),
 (69.0,),
 (74.0,),
 (72.0,),
 (71.0,),
 (72.0,),
 (72.0,),
 (70.0,),
 (73.0,),
 (73.0,),
 (72.0,),
 (73.0,),
 (73.0,),
 (72.0,),
 (63.0,),
 (65.0,),
 (71.0,),
 (76.0,),
 (70.0,),
 (76.0,),
 (69.0,),
 (69.0,),
 (69.0,),
 (74.0,),
 (76.0,),
 (74.0,),
 (73.0,),
 (73.0,),
 (74.0,),
 (73.0,),
 (73.0,),
 (73.0,),
 (74.0,),
 (74.0,),
 (71.0,),
 (73.0,),
 (72.0,),
 (64.0,),
 (66.0,),
 (73.0,),
 (72.0,),
 (65.0,),
 (64.0,),
 (69.0,),
 (68.0,),
 (77.0,),
 (71.0,),
 (71.0,),
 (69.0,),
 (68.0,),
 (68.0,),
 (69.0,),
 (70.0,),
 (72.0,),
 (76.0,),
 (75.0,),
 (69.0,),
 (71.0,),
 (71.0,),
 (71.0,),
 (68.0,),
 (65.0,),
 (70.0,),
 (69.0,),
 (69.0,),
 (71.0,),
 (67.0,),
 (73.0,),
 (74.0,),
 (73.0,),
 (67.0,),
 (74.0,),
 (75.0,),
 (75.0,),
 (74.0,),
 (67.0,),
 (73.0,),
 (73.0,),
 (71.0,),
 (72.0,),
 (71.0,),
 (68.0,),
 (65.0,),
 (69.0,),
 (70.0,),
 (70.0,),
 (74.0,),
 (71.0,),
 (74.0,),
 (73.0,),
 (72.0,),
 (74.0,),
 (72.0,),
 (74.0,),
 (75.0,),
 (74.0,),
 (70.0,),
 (74.0,),
 (70.0,),
 (66.0,),
 (61.0,),
 (63.0,),
 (63.0,),
 (63.0,),
 (63.0,),
 (67.0,),
 (56.0,),
 (75.0,),
 (77.0,),
 (75.0,),
 (75.0,),
 (75.0,),
 (75.0,),
 (71.0,),
 (70.0,),
 (74.0,),
 (74.0,),
 (75.0,),
 (72.0,),
 (70.0,),
 (66.0,),
 (74.0,),
 (75.0,),
 (74.0,),
 (75.0,),
 (76.0,),
 (74.0,),
 (75.0,),
 (74.0,),
 (73.0,),
 (68.0,),
 (73.0,),
 (74.0,),
 (74.0,),
 (77.0,),
 (70.0,),
 (70.0,),
 (69.0,),
 (75.0,),
 (72.0,),
 (69.0,),
 (71.0,),
 (68.0,),
 (67.0,),
 (69.0,),
 (73.0,),
 (70.0,),
 (70.0,),
 (70.0,),
 (66.0,),
 (67.0,),
 (70.0,),
 (66.0,),
 (62.0,),
 (71.0,),
 (73.0,),
 (69.0,),
 (77.0,),
 (74.0,),
 (71.0,),
 (72.0,),
 (74.0,),
 (74.0,),
 (74.0,),
 (74.0,),
 (71.0,),
 (73.0,),
 (69.0,),
 (66.0,),
 (73.0,),
 (72.0,),
 (73.0,),
 (74.0,),
 (73.0,),
 (66.0,),
 (64.0,),
 (66.0,),
 (75.0,),
 (65.0,),
 (69.0,),
 (71.0,),
 (69.0,),
 (78.0,),
 (74.0,),
 (68.0,),
 (68.0,),
 (70.0,),
 (70.0,),
 (71.0,),
 (71.0,),
 (71.0,),
 (71.0,),
 (69.0,),
 (69.0,),
 (72.0,),
 (76.0,),
 (72.0,),
 (73.0,),
 (73.0,),
 (74.0,),
 (69.0,),
 (68.0,),
 (74.0,),
 (73.0,),
 (73.0,),
 (72.0,),
 (71.0,),
 (71.0,),
 (68.0,),
 (72.0,),
 (71.0,),
 (72.0,),
 (71.0,),
 (71.0,),
 (72.0,),
 (71.0,),
 (71.0,),
 (72.0,),
 (72.0,),
 (72.0,),
 (69.0,),
 (71.0,),
 (71.0,),
 (69.0,),
 (74.0,),
 (72.0,),
 (71.0,),
 (71.0,),
 (72.0,),
 (71.0,),
 (67.0,),
 (65.0,),
 (70.0,),
 (76.0,),
 (68.0,),
 (71.0,),
 (71.0,),
 (68.0,),
 (70.0,),
 (73.0,),
 (73.0,),
 (72.0,),
 (71.0,),
 (70.0,),
 (72.0,),
 (71.0,),
 (72.0,),
 (72.0,),
 (71.0,),
 (70.0,),
 (71.0,),
 (71.0,),
 (71.0,),
 (66.0,),
 (65.0,),
 (73.0,),
 (72.0,),
 (72.0,),
 (65.0,),
 (65.0,),
 (68.0,),
 (67.0,),
 (76.0,),
 (70.0,),
 (71.0,),
 (69.0,),
 (67.0,),
 (69.0,),
 (71.0,),
 (69.0,),
 (72.0,),
 (76.0,),
 (75.0,),
 (72.0,),
 (75.0,),
 (71.0,),
 (69.0,),
 (68.0,),
 (68.0,),
 (72.0,),
 (70.0,),
 (72.0,),
 (75.0,),
 (69.0,),
 (72.0,),
 (73.0,),
 (73.0,),
 (72.0,),
 (73.0,),
 (74.0,),
 (73.0,),
 (72.0,),
 (68.0,),
 (72.0,),
 (71.0,),
 (69.0,),
 (67.0,),
 (70.0,),
 (72.0,),
 (67.0,),
 (67.0,),
 (69.0,),
 (67.0,),
 (74.0,),
 (70.0,),
 (73.0,),
 (71.0,),
 (71.0,),
 (71.0,),
 (71.0,),
 (72.0,),
 (76.0,),
 (78.0,),
 (76.0,),
 (73.0,),
 (70.0,),
 (68.0,),
 (77.0,),
 (66.0,),
 (65.0,),
 (69.0,),
 (69.0,),
 (66.0,),
 (64.0,),
 (74.0,),
 (75.0,),
 (80.0,),
 (72.0,),
 (73.0,),
 (70.0,),
 (69.0,),
 (77.0,),
 (74.0,),
 (77.0,),
 (72.0,),
 (69.0,),
 (69.0,),
 (75.0,),
 (75.0,),
 (72.0,),
 (73.0,),
 (78.0,),
 (75.0,),
 (75.0,),
 (74.0,),
 (73.0,),
 (70.0,),
 (70.0,),
 (72.0,),
 (74.0,),
 (74.0,),
 (67.0,),
 (74.0,),
 (70.0,),
 (73.0,),
 (71.0,),
 (71.0,),
 (69.0,),
 (68.0,),
 (70.0,),
 (71.0,),
 (72.0,),
 (70.0,),
 (71.0,),
 (72.0,),
 (68.0,),
 (68.0,),
 (70.0,),
 (70.0,),
 (63.0,),
 (71.0,),
 (67.0,),
 (69.0,),
 (74.0,),
 (72.0,),
 (70.0,),
 (69.0,),
 (73.0,),
 (74.0,),
 (74.0,),
 (73.0,),
 (71.0,),
 (72.0,),
 (69.0,),
 (71.0,),
 (73.0,),
 (73.0,),
 (71.0,),
 (72.0,),
 (71.0,),
 (64.0,),
 (71.0,),
 (62.0,),
 (70.0,),
 (64.0,),
 (64.0,),
 (70.0,),
 (70.0,),
 (69.0,),
 (72.0,),
 (68.0,),
 (68.0,),
 (65.0,),
 (67.0,),
 (68.0,),
 (70.0,),
 (67.0,),
 (73.0,),
 (70.0,),
 (68.0,),
 (72.0,),
 (69.0,),
 (71.0,),
 (70.0,),
 (75.0,),
 (70.0,),
 (68.0,),
 (73.0,),
 (71.0,),
 (71.0,),
 (70.0,),
 (70.0,),
 (70.0,),
 (70.0,),
 (72.0,),
 (74.0,),
 (71.0,),
 (70.0,),
 (70.0,),
 (69.0,),
 (71.0,),
 (70.0,),
 (70.0,),
 (72.0,),
 (72.0,),
 (72.0,),
 (72.0,),
 (72.0,),
 (70.0,),
 (66.0,),
 (71.0,),
 (68.0,),
 (79.0,),
 (76.0,),
 (73.0,),
 (75.0,),
 (71.0,),
 (76.0,),
 (74.0,),
 (73.0,),
 (73.0,),
 (74.0,),
 (73.0,),
 (72.0,),
 (76.0,),
 (75.0,),
 (77.0,),
 (74.0,),
 (76.0,),
 (75.0,),
 (76.0,),
 (73.0,),
 (75.0,),
 (73.0,),
 (73.0,),
 (74.0,),
 (78.0,),
 (78.0,),
 (78.0,),
 (75.0,),
 (75.0,),
 (75.0,),
 (74.0,),
 (77.0,),
 (72.0,),
 (72.0,),
 (73.0,),
 (71.0,),
 (75.0,),
 (76.0,),
 (74.0,),
 (75.0,),
 (74.0,),
 (75.0,),
 (73.0,),
 (72.0,),
 (72.0,),
 (75.0,),
 (74.0,),
 (74.0,),
 (72.0,),
 (73.0,),
 (70.0,),
 (76.0,),
 (78.0,),
 (76.0,),
 (78.0,),
 (74.0,),
 (71.0,),
 (78.0,),
 (70.0,),
 (74.0,),
 (74.0,),
 (75.0,),
 (76.0,),
 (78.0,),
 (72.0,),
 (73.0,),
 (76.0,),
 (72.0,),
 (72.0,),
 (78.0,),
 (76.0,),
 (76.0,),
 (77.0,),
 (79.0,),
 (73.0,),
 (79.0,),
 (77.0,),
 (78.0,),
 (76.0,),
 (78.0,),
 (77.0,),
 (79.0,),
 (75.0,),
 (77.0,),
 (76.0,),
 (78.0,),
 (78.0,),
 (77.0,),
 (78.0,),
 (78.0,),
 (76.0,),
 (75.0,),
 (72.0,),
 (75.0,),
 (77.0,),
 (75.0,),
 (77.0,),
 (76.0,),
 (76.0,),
 (75.0,),
 (72.0,),
 (76.0,),
 (75.0,),
 (72.0,),
 (72.0,),
 (75.0,),
 (69.0,),
 (75.0,),
 (74.0,),
 (78.0,),
 (77.0,),
 (76.0,),
 (72.0,),
 (73.0,),
 (74.0,),
 (74.0,),
 (74.0,),
 (73.0,),
 (73.0,),
 (71.0,),
 (72.0,),
 (72.0,),
 (75.0,),
 (66.0,),
 (66.0,),
 (67.0,),
 (76.0,),
 (68.0,),
 (69.0,),
 (71.0,),
 (70.0,),
 (68.0,),
 (66.0,),
 (69.0,),
 (69.0,),
 (71.0,),
 (72.0,),
 (69.0,),
 (72.0,),
 (70.0,),
 (76.0,),
 (69.0,),
 (71.0,),
 (72.0,),
 (71.0,),
 (78.0,),
 (73.0,),
 (74.0,),
 (68.0,),
 (71.0,),
 (76.0,),
 (75.0,),
 (74.0,),
 (73.0,),
 (73.0,),
 (74.0,),
 (69.0,),
 (74.0,),
 (72.0,),
 (70.0,),
 (67.0,),
 (69.0,),
 (73.0,),
 (75.0,),
 (74.0,),
 (72.0,),
 (71.0,),
 (67.0,),
 (74.0,),
 (70.0,),
 (70.0,),
 (70.0,),
 (71.0,),
 (70.0,),
 (71.0,),
 (71.0,),
 (68.0,),
 (74.0,),
 (75.0,),
 (74.0,),
 (77.0,),
 (76.0,),
 (77.0,),
 (75.0,),
 (76.0,),
 (75.0,),
 (77.0,),
 (75.0,),
 (77.0,),
 (74.0,),
 (78.0,),
 (77.0,),
 (76.0,),
 (69.0,),
 (70.0,),
 (64.0,),
 (75.0,),
 (69.0,),
 (65.0,),
 (76.0,),
 (81.0,),
 (71.0,),
 (71.0,),
 (71.0,),
 (82.0,),
 (74.0,),
 (75.0,),
 (77.0,),
 (74.0,),
 (68.0,),
 (72.0,),
 (70.0,),
 (68.0,),
 (74.0,),
 (71.0,),
 (70.0,),
 (70.0,),
 (70.0,),
 (68.0,),
 (68.0,),
 (68.0,),
 (66.0,),
 (71.0,),
 (76.0,),
 (73.0,),
 (70.0,),
 (68.0,),
 (71.0,),
 (71.0,),
 (68.0,),
 (71.0,),
 (70.0,),
 (73.0,),
 (78.0,),
 (76.0,),
 (73.0,),
 (74.0,),
 (63.0,),
 (72.0,),
 (75.0,),
 (74.0,),
 (72.0,),
 (68.0,),
 (74.0,),
 (73.0,),
 (73.0,),
 (72.0,),
 (73.0,),
 (72.0,),
 (78.0,),
 (74.0,),
 (74.0,),
 (78.0,),
 (78.0,),
 (61.0,),
 (69.0,),
 (65.0,),
 (77.0,),
 (67.0,),
 (69.0,),
 (75.0,),
 (67.0,),
 (71.0,),
 (74.0,),
 (66.0,),
 (66.0,),
 (77.0,),
 (70.0,),
 (73.0,),
 (71.0,),
 (71.0,),
 (71.0,),
 (67.0,),
 (71.0,),
 (74.0,),
 (76.0,),
 (72.0,),
 (74.0,),
 (75.0,),
 (69.0,),
 (69.0,),
 (69.0,),
 (75.0,),
 (73.0,),
 (73.0,),
 (72.0,),
 (72.0,),
 (72.0,),
 (74.0,),
 (72.0,),
 (73.0,),
 (73.0,),
 (73.0,),
 (73.0,),
 (74.0,),
 (73.0,),
 (71.0,),
 (72.0,),
 (73.0,),
 (74.0,),
 (72.0,),
 (73.0,),
 (73.0,),
 (71.0,),
 (73.0,),
 (75.0,),
 (71.0,),
 (72.0,),
 (73.0,),
 (71.0,),
 (65.0,),
 (77.0,),
 (72.0,),
 (78.0,),
 (71.0,),
 (72.0,),
 (71.0,),
 (72.0,),
 (76.0,),
 (75.0,),
 (75.0,),
 (76.0,),
 (73.0,),
 (72.0,),
 (74.0,),
 (74.0,),
 (74.0,),
 (73.0,),
 (77.0,),
 (73.0,),
 (70.0,),
 (72.0,),
 (76.0,),
 (65.0,),
 (74.0,),
 (73.0,),
 (77.0,),
 (76.0,),
 (69.0,),
 (78.0,),
 (76.0,),
 (68.0,),
 (76.0,),
 (68.0,),
 (79.0,),
 (69.0,),
 (64.0,),
 (70.0,),
 (69.0,),
 (73.0,),
 (70.0,),
 (74.0,),
 (76.0,),
 (76.0,),
 (69.0,),
 (73.0,),
 (73.0,),
 (65.0,),
 (70.0,),
 (72.0,),
 (72.0,),
 (75.0,),
 (74.0,),
 (69.0,),
 (73.0,),
 (75.0,),
 (76.0,),
 (74.0,),
 (73.0,),
 (74.0,),
 (71.0,),
 (72.0,),
 (73.0,),
 (72.0,),
 (72.0,),
 (73.0,),
 (72.0,),
 (75.0,),
 (76.0,),
 (67.0,),
 (69.0,),
 (70.0,),
 (75.0,),
 (74.0,),
 (71.0,),
 (74.0,),
 (71.0,),
 (72.0,),
 (74.0,),
 (75.0,),
 (73.0,),
 (75.0,),
 (76.0,),
 (68.0,),
 (71.0,),
 (68.0,),
 (66.0,),
 (63.0,),
 (62.0,),
 (67.0,),
 (68.0,),
 (63.0,),
 (56.0,),
 (76.0,),
 (75.0,),
 (74.0,),
 (76.0,),
 (69.0,),
 (71.0,),
 (72.0,),
 (74.0,),
 (75.0,),
 (72.0,),
 (78.0,),
 (69.0,),
 (75.0,),
 (75.0,),
 (74.0,),
 (74.0,),
 (76.0,),
 (73.0,),
 (75.0,),
 (75.0,),
 (74.0,),
 (79.0,),
 (75.0,),
 (76.0,),
 (76.0,),
 (69.0,),
 (72.0,),
 (76.0,),
 (75.0,),
 (75.0,),
 (75.0,),
 (70.0,),
 (70.0,),
 (74.0,),
 (73.0,),
 (72.0,),
 (78.0,),
 (67.0,),
 (69.0,),
 (71.0,),
 (74.0,),
 (63.0,),
 (76.0,),
 (76.0,),
 (71.0,),
 (76.0,),
 (77.0,),
 (73.0,),
 (71.0,),
 (78.0,),
 (78.0,),
 (75.0,),
 (75.0,),
 (72.0,),
 (77.0,),
 (72.0,),
 (72.0,),
 (71.0,),
 (72.0,),
 (74.0,),
 (66.0,),
 (61.0,),
 (58.0,),
 (60.0,),
 (71.0,),
 (65.0,),
 (72.0,),
 (70.0,),
 (68.0,),
 (67.0,),
 (71.0,),
 (65.0,),
 (64.0,),
 (65.0,),
 (69.0,),
 (70.0,),
 (70.0,),
 (68.0,),
 (69.0,),
 (71.0,),
 (70.0,),
 (71.0,),
 (76.0,),
 (71.0,),
 (72.0,),
 (73.0,),
 (77.0,),
 (67.0,),
 (69.0,),
 (72.0,),
 (74.0,),
 (71.0,),
 (70.0,),
 (68.0,),
 (70.0,),
 (66.0,),
 (72.0,),
 (70.0,),
 (70.0,),
 (70.0,),
 (70.0,),
 (73.0,),
 (71.0,),
 (69.0,),
 (73.0,),
 (72.0,),
 (71.0,),
 (69.0,),
 (70.0,),
 (69.0,),
 (70.0,),
 (75.0,),
 (71.0,),
 (70.0,),
 ...]

In [60]:
# Convert the December temperatures to a list.
dec_temps = []
dec_temps = session.query(Measurement.tobs).filter(func.extract('month', Measurement.date)== 12).all()

In [59]:
# Create a DataFrame from the list of temperatures for the month of December. 
dec_temps_df = pd.DataFrame(dec_temps, columns = ['December Temps'])
dec_temps_df

      December Temps
0               76.0
1               74.0
2               74.0
3               64.0
4               64.0
...              ...
1512            71.0
1513            71.0
1514            69.0
1515            65.0
1516            65.0

[1517 rows x 1 columns]

In [61]:
# Calculate and print out the summary statistics for the Decemeber temperature DataFrame.
dec_temps_df.describe()

       December Temps
count     1517.000000
mean        71.041529
std          3.745920
min         56.000000
25%         69.000000
50%         71.000000
75%         74.000000
max         83.000000

In [87]:
#add query to get rainfall for June
june_rain = []
june_rain = session.query(Measurement.prcp).filter(func.extract('month', Measurement.date)== 6).all()

In [96]:
june_rain_df = pd.DataFrame(june_rain, columns = ["June Rainfall"])

In [97]:
june_rain_df.describe()

       June Rainfall
count    1574.000000
mean        0.136360
std         0.335731
min         0.000000
25%         0.000000
50%         0.020000
75%         0.120000
max         4.430000

In [90]:
#add query to get rainfall for December
dec_rain = []
dec_rain = session.query(Measurement.prcp).filter(func.extract('month', Measurement.date)== 12).all()

In [98]:
dec_rain_df = pd.DataFrame(dec_rain, columns = ["December Rainfall"])

In [99]:
dec_rain_df.describe()

       December Rainfall
count        1405.000000
mean            0.216819
std             0.541399
min             0.000000
25%             0.000000
50%             0.030000
75%             0.150000
max             6.420000

In [93]:
#add query to get rainfall for whole year
rain = []
rain = session.query(Measurement.prcp).all()

In [100]:
rain_df = pd.DataFrame(rain, columns = ["Rainfall"])

In [101]:
rain_df.describe()

           Rainfall
count  18103.000000
mean       0.160644
std        0.468746
min        0.000000
25%        0.000000
50%        0.010000
75%        0.110000
max       11.530000